Repository Sirajmolla/Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#2 Add files via upload
  1-two-sum.cpp
Labels: Hacktoberfest Accepted

#1 Added Calculator.c file
  Calculator.c
Labels: Hacktoberfest Accepted

#3 Stack Program
  BYARRAY.CPP
  BYLINK.CPP
  DECTOBIN.CPP
  PAREN1.CPP
  POSTFIX.CPP
  PROG1.CPP
  PROG2.CPP
  infixtopost.cpp
  infixtoprefix.cpp
Labels: Hacktoberfest Accepted

#4 FIRST_PR_OJECT ino
  FIRST_PR_OJECT.ino
Labels: Hacktoberfest Accepted

#5 Kth Largest Element in an Array
  Kth Largest Element in an Array.cpp
Labels: Hacktoberfest Accepted

#6 Two Pointers array problem in C++
  three-sum.cpp
Labels: Hacktoberfest Accepted

#7 Create Turtle.py
  Turtle.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#8 Create divide-two-integers.cpp
  divide-two-integers.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#9 Added Big M algorithm
  bigm.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#10 Generate Parenthesis.cpp
  Generate Parenthesis.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#13 Create count-sort.cpp
  count-sort.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#12 added new and medium level difficulty questions
  132 Pattern.cpp
  Grid Unique Paths.cpp
  Pow(X,n).cpp
  Search in a 2d Matrix.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#11 Create bubblesort.c
  bubblesort.c
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#14 Create HelloWorld.sol
  Solidity/HelloWorld.sol
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#16 Added subarray with given sum in c++
  Subarray with given sum.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#15 add: calculate age :rocket:
  CalculatorAge.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#17 added program for Best Time to Buy and Sell Stock
  buyAndSell.js
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#19 Array Cloning using Java
  Array_Clone.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#20 Lambda Expression using Java
  LambdaExpression.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#22 Array Passing Using Java
  Array_Passing.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#23 Split the array and add the first part to the end
  splitTheArray.js
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#24 Heap sort-hacktoberfest-2022
  HeapSort
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#25 currency formatter
  currencyFormatter.js
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#26 Create Simple fun animation try it
  Simple fun animation try it
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#28 MergeSort
  MergeSort.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#27 Stack Program Added
  Stack.cpp
  participant_details.json
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#29 A python program using Tkinter
  mile_to_km_coverter.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#31 add one encryption algorithm
  caser-cipher.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#32 Create FizzBuzz.py
  FizzBuzz.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#35 Create Stack Sort Program
  Stack_Sort.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#34 Instragram Bot
  instra_bot.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#33 Added java program to check whether a word is palindrome or not
  PalindromeWord.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#36 Create Sending SMS and smart lighting
  Sending SMS and smart lighting
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#39 Birthday_reminder
  Birthday_reminder.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#38 cpp program to check armstrong number
  armstrong.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#40 Create code to FIND any ELEMENT INDEX using LINEAR SEARCH.CPP
  code to FIND any ELEMENT INDEX using LINEAR SEARCH.CPP
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#41 Added karatsuba algorithm for fast multiplication
  Karatsuba_algo.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#42 Breadth First Search Algorithm
  BFS.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#43 reverse string using stack
  reverse string using stack.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#44 Added Golang file for beginners
  main.go
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#45 create basic operations listmap.scala
  ListMap.scala
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#46 created ladderBottomUP.cpp with O(N) TC
  ladderBottomUP.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#47 Linked list traversal
  Linked list traversal
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#48 Library Management System in C++ Added
  Library_Management_System.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#62 created hostelVisit.cpp using proiorityQueue ( heap )
  hostelVisit.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#61 created joinRopes.cpp using priorityQueue (heap)
  joinRopes.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#60 created heapSorting.cpp
  heapSorting.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#59 created buildHeap.cpp for min & max heap
  buildHeap.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#57 I added Merge Sort in C++
  Merge_sort.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#56 Create LargestOfThree.py
  LargestOfThree.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#55 Create HCF.py
  HCF.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#54 Create NumberConversion.py
  NumberConversion.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#64 created BuildingBST.cpp (binarySearchTree)
  BuildingBST.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#53 Create Factorial.py
  Factorial.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#52 Create TwoSum.py
  TwoSum.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#66 Added merge_sort in c++
  quick_sort.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#65 A basic snake game using python
  rock paper scissor.py
  snake game.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#67 created searchBST.cpp
  searchBST.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#51 Sum of two arrays
  sum_of_two_array.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#68 created treeToLinkedList.cpp
  treeToLinkedList.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#49 created beginerIntro.kt for kickstat in android kotlin
  beginerIntro.kt
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#69 created sumAtLevelK.cpp
  sumAtLevelK.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#71 create star pattern for any number of rows
  starPattern.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#73 add tictactoegame
  TicTacToeGame/index.html
  TicTacToeGame/script.js
  TicTacToeGame/style.css
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#77 Added a movie recommendation system webapp
  Movie recommendation web app/.gitignore
  Movie recommendation web app/1.6.png
  Movie recommendation web app/1.7.png
  Movie recommendation web app/Architecture.jpg
  Movie recommendation web app/Classifier.py
  Movie recommendation web app/DEVELOPMENT_CYCLE.jpg
  Movie recommendation web app/Data.ipynb
  Movie recommendation web app/README.md
  Movie recommendation web app/api.py
  Movie recommendation web app/app.py
  Movie recommendation web app/data.db
  Movie recommendation web app/data.json
  Movie recommendation web app/data1.db
  Movie recommendation web app/heading.png
  Movie recommendation web app/hel.gif
  Movie recommendation web app/hello.gif
  Movie recommendation web app/movie_metadata.csv
  Movie recommendation web app/requirements.txt
  Movie recommendation web app/setup.sh
  Movie recommendation web app/style.css
  Movie recommendation web app/titles.json
  Movie recommendation web app/we.png
  Movie recommendation web app/we3.jpg
  Movie recommendation web app/we3.webp
  Movie recommendation web app/we4.jpeg
  Movie recommendation web app/we5.png
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#76 updated readme
  README.md
  images/hacktoberfest (1).png
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#75 Update README.md
  README.md
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#81 Added Matrix Multiplication in C
  C/matrix multiplication.c
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#80 Create Remove_dublicated_from_sortedArry.cxx
  C++/Remove_dublicated_from_sortedArry.cxx
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#82 added "tictactoe.py"
  Python/tictactoe.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#83 added music player
  Python/music_player.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#84 turtle race game
  Python/turtle race.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#86 Binary_tree.cpp
  C++/Binary_tree.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#85 Create Pascal's Triangle using Java
  Pascal'sTriangle.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#87 Hot Coffee cup using Html, CSS and Jscript
  Hot cup.html
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#88 Slider using Html and CSS
  slider.html
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#89 Hover effect on Button using html and css
  Button Hover.html
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#90 Calculator using html css and js
  Calculator.html
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#91 Added code for Bitwise XOR
  Python/bitwise_XOR.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#92 Create Longest Palindromic Substring.py
  Python/Longest Palindromic Substring.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#94 Create Multiply-two-matrices.py
  Python/Multiply-two-matrices.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#96 Added python program to check for prime number
  Python/primenumber.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#97 Added python program to get largest prime factor of a number
  Python/largest_prime_factor.py
  Python/n_largest_elements.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#98 detects fake news
  python/fakenewsdetection.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#99 added Interval Prime Number code
  Python/IntervalPrimeNumbers.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#100 Write a program to print the Fibonacci series up to a given number
  Python/fibonaccifunction.py
  contributors.md
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#101 Add Bubble Sort
  Python/BubbleSort.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#102 Added Merge K sorted list c++
  C++/Merge K Sorted Lists.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#103 add Devto Posts scraper via public API
  Python/devto_posts_backup.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#104 hierarchical_inheritance
  C++/constructors_destructors.cpp
  C++/function_overloading.cpp
  C++/hierarchical_inheritance.cpp
  C++/static_datamember_functions.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#105 Added to mergesort
  Bubble sort.txt
  mergesort.txt
  quicksort.txt
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#106 Create FibonacciIter.py
  Python/FibonacciIter.py
  Python/FibonacciRec.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#107 Create c++algo.cpp
  C++/c++algo.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#108 Add Magic_Number.py
  Python/Magic_Number.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#109 Created C program of Singly linked list.
  C/LinkedListInsertionAtSpecificPosition.c
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#110 Added graph solution
  Java/graph.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#112 Create C codes
  C/double_triangle.c
  C/guessing_the_number.c
  C/square.c
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#111 hacktoberfest-2022
  Java/armstrong.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#113 Add files via upload
  Python/dfs_bfs.py
  Python/guess-the-number.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#114 Add files via upload
  Quick Select Algorithm in C++.cpp
  floyds_cycle_detection.cpp
  kmp.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#116 Create seat_occupation.java
  Java/seat_occupation.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#115 Create simple_password_generator.py
  Python/simple_password_generator.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#117 Group Anagrams
  Python/Group Anagrams.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#118 added min-max norm method
  Python/MinMaxNorm.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#119 graph basics
  C++/bfs.cpp
  C++/dfs.cpp
  C++/primscode.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#120 adding fire detection project in python
  fire-detection/main.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#122 Added new c++ leetcode solution
  C++/Find_First_and_last_Position_of_Element_in_Sorted_Array.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#121 new c++ solution added
  C++/longest_Palindrome_String.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#123 Create SortingCards.java
  Java/SortingCrads.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#124 Create BMICalculator.py
  Python/BMICalculator.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#125 Adding Line Following Robot Code
  Arduino/Line Following Robot Code
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#126 Check whether given number is the prime or not
  Python/Check whether a number is Prime or not.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#128 Coffee Winding Machine Python Program
  coffeewindingmachine.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#131 Check prime number or not
  Java/Checl_Prime.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#130 binary search algorithm
  Python/binary_search.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#133 Find ASCII value of characters in a string
  Python/Find the ASCII value of the characters in a string.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#132 Twitter-Retweet-bot
  Python/Twitter-RT-bot/README.md
  Python/Twitter-RT-bot/twitter-bot.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#134 Find the area of circle
  Python/All positive number in a range.py
  Python/Find the area of a circle.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#136 Added a C program of array traversal.
  C/Array_traversal.c
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#135 program to find lagranges interpolation
  Cpp/Lagrange_s Interpolation.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#137 add unzip file code python
  Python/unzipfile.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#138 Added Youtube playlist downloader python file as ytDownloader.py
  Python/ytDownloader.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#139 Added Binary Search in Java
  Java/Binary_Search.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#144 Create infix-to-postfix.c
  C/infix-to-postfix.c
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#145 Added linked list
  C++/bfs.cpp
  Cpp/linked-list.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#147 Add files via upload
  sudoku through pygame.py
Labels: Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#146 Create LeapYear.java
  Java/LeapYear.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#149 Merge Sort
  python/Merge Sort.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#148 Add files via upload
  Python/lengthconv.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#150 java linkedlist -> size() , print() , add() , addlast() , addfirst() …
  Java/linkedlist.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#151 JAVA stack - push() , pop() , peek () ;
  Java/stack.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#152 Add drum kit made with HTML
  drum kit/images/crash.png
  drum kit/images/kick.png
  drum kit/images/snare.png
  drum kit/images/tom1.png
  drum kit/images/tom2.png
  drum kit/images/tom3.png
  drum kit/images/tom4.png
  drum kit/index.html
  drum kit/index.js
  drum kit/sounds/crash.mp3
  drum kit/sounds/kick-bass.mp3
  drum kit/sounds/snare.mp3
  drum kit/sounds/tom-1.mp3
  drum kit/sounds/tom-2.mp3
  drum kit/sounds/tom-3.mp3
  drum kit/sounds/tom-4.mp3
  drum kit/styles.css
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#153 Added Some C++ Programs
  C++/Binary_substitution.cpp
  C++/Book_Allocation.cpp
  C++/Building a heap using cpp
  C++/C++ Program to Reverse an Integer
  C++/EnvelopePattern.cpp
  C++/FindPeakElementA.cpp
  C++/Merge Two Sorted Lists.cpp
  C++/Permutations in C++.cpp
  C++/ReverseNo.cpp
  C++/Trapping Rain Water.c++
  C++/binary_search.cpp
  C++/longest_common_subsequence_dp.cpp
  C++/richest-customer-wealth.cpp
  C++/vertical_order_bt.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#156 Removedor de números pares
  Python/Tutorial/remove_pairs.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#155 Created img2jpeg
  Python/img2jpeg.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#157 Add new problem
  Java/RainWater.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#161 Contdown Timer code in python
  Python/countdowntimer.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#160 added hangman python simple game
  Python/hangman_game.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#159 Modified Python/Factorial.py
  python/Factorial.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#158 Java Swing GUI Swap Two Numbers Program
  Java/swap_swings.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#162 added prime numbers list comprehension
  Python/prime_list_comprehension.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#163 Add quick sort
  quick_sort/QuickSort.c
  quick_sort/QuickSort.class
  quick_sort/QuickSort.cpp
  quick_sort/QuickSort.exe
  quick_sort/QuickSort.java
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#166 added balanced_paranthesis exercise
  Python/balanced_paranthesis.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#169 created Longest common subsequence in cpp
  C++/LongestCommonSubsequence.cpp
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#173 Fetch COVID 19 data via API
  CodeP25_29Mar.jpg
  OutputP25_29Mar.jpg
  P25_29Mar.py
  python/CodeP25_29Mar.jpg
  python/OutputP25_29Mar.jpg
  python/P25_29Mar.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#172 flappy word game
  flappywordgame.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#174 Create Readme
  Python/Complete stack and Queue in Python/Readme
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#175 stack imp. question pattern solution in python
  Python/stack_SDE.py
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#178 A responsive contact us page
  contact form/contact.html
  contact form/images/bck.jpg
  contact form/services.css
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest

#176 pystuff
  Python/BannerGrab.py
  contributors.md
Labels: HACKTOBERFEST-ACCEPTED, Hacktoberfest Accepted, Hacktoberfest2022, Hacktoberfest
